package com.bvas.bvas.model.enums;

public enum AuditAction {
    BILL_SUBMITTED,
    BILL_APPROVED,
    BILL_REJECTED,
    BILL_RESUBMITTED,
    USER_CREATED,
    USER_UPDATED,
    USER_BLOCKED,
    SUBMISSION_WINDOW_LOCKED,
    SUBMISSION_WINDOW_UNLOCKED,
    DIGITAL_SIGNATURE_APPLIED
}